import Providers from 'src/app/Providers';
import './globals.scss';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { twMerge } from 'tailwind-merge';
import Sidebar from '@/components/sidebar';

const montserrat = Montserrat({ subsets: [ 'latin' ] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => (
  <html lang='en'>
    <body className={ twMerge('bg-slate-300 flex', montserrat.className) }>
      <Sidebar />
      <Providers>{children}</Providers>
    </body>
  </html>
);

export default RootLayout;
